#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
#
# Obtain a Let's Encrypt certificate for the Oryx mgmt UI and keep it
# auto-renewed. No app changes are needed: this fork keeps Oryx's cert
# hot-reload (reloadCertificateFile), which re-reads
#   <oryx-data>/config/nginx.key  and  <oryx-data>/config/nginx.crt
# on a timer. We point certbot's renewal deploy-hook at those files, so each
# renewal is picked up automatically with zero downtime (no container restart,
# so live streams are never interrupted).
#
# How renewal works: installing certbot also installs its systemd timer
# (certbot.timer, runs twice daily). On renewal it runs every script in
# /etc/letsencrypt/renewal-hooks/deploy/, including the one this script writes.
#
# Requirements:
#   - A DNS name (A record) pointing at this VM's public IP.
#   - Inbound TCP 80 open on the NSG (HTTP-01 standalone is used at issuance and
#     at each renewal). Add it with:
#       RG=<rg> NSG=<nsg> az network nsg rule create -g $RG --nsg-name $NSG \
#         -n Allow-HTTP --priority 1005 --direction Inbound --access Allow \
#         --protocol Tcp --destination-port-ranges 80 --source-address-prefixes '*'
#
# Usage:
#   DOMAIN=oryx.example.com EMAIL=you@example.com ./certbot-setup.sh
#
# Optional env:
#   DATA_DIR   Oryx data dir on the host (default: $HOME/oryx-data)
#   CONTAINER  Oryx container name for the one-time apply (default: oryx)
set -euo pipefail

DOMAIN="${DOMAIN:?set DOMAIN to your fully-qualified hostname (A record -> this VM)}"
EMAIL="${EMAIL:?set EMAIL for certificate expiry notices}"
DATA_DIR="${DATA_DIR:-$HOME/oryx-data}"
CONTAINER="${CONTAINER:-oryx}"

# Absolute paths baked into the hook (it runs as root from the systemd timer,
# where $HOME is /root — so we must not rely on ~ inside the hook).
KEY_DST="$DATA_DIR/config/nginx.key"
CRT_DST="$DATA_DIR/config/nginx.crt"

if [ ! -d "$DATA_DIR/config" ]; then
  echo "ERROR: $DATA_DIR/config not found. Start the oryx container once (so it" >&2
  echo "       creates its data dir) before running this." >&2
  exit 1
fi

echo "Installing certbot..."
sudo apt-get update -y
sudo apt-get install -y certbot

# Renewal deploy-hook: copy the freshly issued/renewed cert into Oryx's cert
# files. Oryx's hourly reloadCertificateFile cron then serves it (no restart).
HOOK=/etc/letsencrypt/renewal-hooks/deploy/oryx.sh
echo "Writing renewal deploy-hook: $HOOK"
sudo mkdir -p "$(dirname "$HOOK")"
sudo tee "$HOOK" >/dev/null <<EOF
#!/usr/bin/env bash
# Auto-generated by certbot-setup.sh — installs the renewed cert into Oryx.
set -e
install -m 600 "/etc/letsencrypt/live/${DOMAIN}/privkey.pem"   "${KEY_DST}"
install -m 644 "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" "${CRT_DST}"
EOF
sudo chmod +x "$HOOK"

echo "Requesting certificate for $DOMAIN (HTTP-01, standalone on :80)..."
sudo certbot certonly --standalone --non-interactive --agree-tos \
  -m "$EMAIL" -d "$DOMAIN" --deploy-hook "$HOOK"

# certonly runs the deploy-hook on success, so the cert is already in place.
# Restart once to apply immediately (renewals afterwards are picked up live by
# Oryx's reload cron, so they will NOT restart the container).
if command -v docker >/dev/null 2>&1 && docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "Restarting $CONTAINER once to apply the initial cert..."
  docker restart "$CONTAINER" >/dev/null || sudo docker restart "$CONTAINER" >/dev/null || true
fi

cat <<EOF

Done. https://${DOMAIN}/mgmt now serves a trusted Let's Encrypt cert.
Auto-renewal is handled by the certbot systemd timer; verify with:
  systemctl list-timers certbot.timer
  sudo certbot renew --dry-run
EOF
